apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: finn-kandidat-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  team: {{team}}
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/finn-kandidat-api/
    - https://app-q0.adeo.no/finn-kandidat-api/
  liveness:
    path: /finn-kandidat-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /finn-kandidat-api/internal/actuator/health
    initialDelay: 30
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvfinn-kandidat-api
        mountPath: /secret/serviceuser
  webproxy: false
  prometheus:
    enabled: true
    path: /finn-kandidat-api/internal/actuator/prometheus
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - configmap: loginservice-idporten
