apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: tillretteleggingsbehov-1
  namespace: toi
  labels:
    team: toi
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact,delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 438500 #Litt over 50 år
  acl:
    - team: arbeidsgiver
      application: finn-kandidat-api
      access: readwrite
    - team: toi
      application: toi-tilretteleggingsbehov
      access: read
    - team: arbeidsgiver-inkludering
      application: arbeidsgiver-inkludering-kafkamanager
      access: read
