apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: finn-kandidat-api-alert
  labels:
    team: teamtag
spec:
  receivers:
    slack:
      channel: 'tag-notifications'
      prependText: '<!here> '
  alerts:
    - alert: Konsumering av avsluttet oppfølging melding feilet
      expr: sum(increase(finnkandidat_avsluttetoppfolging_feilet_total[5m])) > 0
      for: 1m
      action: "Gå i Kibana og søk etter følgende for de siste 10 min: application:finn-kandidat-api AND envclass:p AND level:Error"
