version: 2.1
orbs:
  nais: navikt/nais-deployment@3.2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          name: Hent Maven cache
          keys:
            - m2-{{ .Branch }}-{{ checksum "pom.xml" }}
            - m2-{{ checksum "pom.xml" }}
            - m2-
      - run:
          name: Bygg med Maven
          command: mvn clean package
      - save_cache:
          name: Lagre Maven cache
          key: m2-{{ .Branch }}-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - nais/docker:
          image: navikt/finn-kandidat-api

  deploy-til-dev:
    docker:
      - image: navikt/deployment-cli:0.4.2
    steps:
      - checkout
      - run:
          name: Unpack Private Key
          command: echo $GITHUB_PRIVATE_KEY | base64 -d > .circleci/github.key.pem
      - nais/deploy-with-gh-app:
          repo: navikt/finn-kandidat-api
          image: navikt/finn-kandidat-api
          github-app-id: 43789
          nais-template: nais-dev-fss.yaml
          environment: dev-fss
          team: teamtag

  deploy-til-prod:
    docker:
      - image: navikt/deployment-cli:0.4.2
    steps:
      - checkout
      - run:
          name: Unpack Private Key
          command: echo $GITHUB_PRIVATE_KEY | base64 -d > .circleci/github.key.pem
      - nais/deploy-with-gh-app:
          repo: navikt/finn-kandidat-api
          image: navikt/finn-kandidat-api
          github-app-id: 43789
          nais-template: nais-prod-fss.yaml
          environment: prod-fss
          team: teamtag

workflows:
  version: 2.1
  bygg_og_deploy:
    jobs:
      - build:
          context: NAIS deployment
      - deploy-til-dev:
          context: tag-ci
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - valider-openam-tokens
      - godkjenn-til-prod:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-til-prod:
          context: tag-ci
          requires:
            - godkjenn-til-prod
          filters:
            branches:
              only:
                - master
