apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: finn-kandidat-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  groups:
    - name: finn-kandidat-api
      rules:
        - alert: finn-kandidat-api
          expr: kube_deployment_status_replicas_available{deployment="finn-kandidat-api"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/ppcyL"
          labels:
            namespace: toi
            severity: critical

        - alert: finn-kandidat-api
          expr: sum(increase(logd_messages_total{log_app="finn-kandidat-api",log_level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/ppcyL"
          labels:
            namespace: toi
            severity: critical

        - alert: finn-kandidat-api
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="finn-kandidat-api",log_level=~"Warning"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="finn-kandidat-api"}[3m]))) > 5
          for: 3m
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/ppcyL"
          labels:
            namespace: toi
            severity: warning

        - alert: finn-kandidat-api
          expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^5\\d\\d", backend=~"arbeidsgiver.nais.*/finn-kandidat-api/*"}[3m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"arbeidsgiver.nais.*/finn-kandidat-api/*"}[3m])))) > 1
          for: 3m
          annotations:
            summary: Økning i HTTP-serverfeil (5xx-responser)
            action: "https://logs.adeo.no/app/r/s/ppcyL"
          labels:
            namespace: toi
            severity: warning

        - alert: finn-kandidat-api
          expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^4\\d\\d", backend=~"arbeidsgiver.nais.*/finn-kandidat-api/*"}[3m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"arbeidsgiver.nais.*/finn-kandidat-api/*"}[3m])))) > 1
          for: 3m
          annotations:
            summary: Økning HTTP-klientfeil (4xx-responser)
            action: "https://logs.adeo.no/app/r/s/ppcyL"
          labels:
            namespace: toi
            severity: warning
