apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: finn-kandidat-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 8080
  resources:
    limits:
      memory: 2048Mi
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/finn-kandidat-api/
    - https://app.adeo.no/finn-kandidat-api/
    - https://finn-kandidat-api.prod-fss-pub.nais.io/finn-kandidat-api/
  liveness:
    path: /finn-kandidat-api/internal/actuator/health
    initialDelay: 90
  readiness:
    path: /finn-kandidat-api/internal/actuator/health
    initialDelay: 90
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfinn-kandidat-api
        mountPath: /secret/serviceuser
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  webproxy: false
  prometheus:
    enabled: true
    path: /finn-kandidat-api/internal/actuator/prometheus
  azure:
    application:
      enabled: true
      # Tillat alle siden vi har egen tilgangskontroll i ABAC
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: tilretteleggingsbehov-innsyn
          cluster: prod-gcp
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
