name: Deploy tilretteleggingsbehov-topic to prod

on:
  push:
    branches:
      - master
    paths:
      - topic-tilrettelegginsbehov-prod.yaml
      - .github/workflows/deploy-tilrettelegginsbehov-topic-to-prod.yaml

jobs:
  deploy-rapid-to-prod:
    name: Deploy rapid-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_TOI }}
          CLUSTER: prod-gcp
          RESOURCE: topic-tilrettelegginsbehov-prod.yaml